### ISSUE TITLE
Create Frontend

### ISSUE THREAD

**Issue by rjnay1984** [rjnay1984/LocalLibrary#3]
I've decided that NextJS will be the frontend of choice here.

### Todo:

- [ ] Generate NextJS project
- [ ] Add Jest Testing
- [ ] Add Cypress Testing
- [ ] Add Eslint with prettier
